# Generated by Django 4.2 on 2023-04-08 02:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('cor', models.CharField(choices=[('preto', 'Preto'), ('branco', 'Branco'), ('cinza', 'Cinza'), ('marrom', 'Marrom'), ('caramelo', 'Caramelo')], max_length=10)),
                ('idade', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('cidade', models.CharField(blank=True, max_length=30, null=True)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(max_length=2000)),
                ('telefone_contato', models.CharField(blank=True, max_length=13, null=True)),
                ('status', models.CharField(choices=[('D', 'Disponivel para adoção'), ('A', 'Adoção em Andamento'), ('F', 'Adoção finalizada')], max_length=1)),
                ('foto', models.ImageField(upload_to='Animais/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('porte', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=1)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais.especies')),
            ],
        ),
    ]
