# Generated by Django 4.2 on 2023-04-08 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raca',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais.especies'),
        ),
    ]
