# Generated by Django 4.2 on 2023-04-08 03:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_alter_raca_especie'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='raca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animais.raca'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='cidade',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='cor',
            field=models.CharField(choices=[('preto', 'Preto'), ('branco', 'Branco'), ('cinza', 'Cinza'), ('marrom', 'Marrom'), ('caramelo', 'Caramelo')], max_length=10, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='data_entrada',
            field=models.DateField(blank=True, null=True, verbose_name='Data de entrada no abrigo'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='descricao',
            field=models.TextField(max_length=2000, verbose_name='Descrição da história do animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=models.ImageField(upload_to='Animais/%Y/%m/%d', verbose_name='Foto do animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('D', 'Disponivel para adoção'), ('A', 'Adoção em Andamento'), ('F', 'Adoção finalizada')], max_length=1, verbose_name='Status de adoção'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefone para contato'),
        ),
        migrations.AlterField(
            model_name='especies',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='raca',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais.especies', verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='raca',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='raca',
            name='porte',
            field=models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=1, verbose_name='Porte'),
        ),
    ]
