# Generated by Django 4.2 on 2023-04-08 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_animal_raca_alter_animal_cidade_alter_animal_cor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especies',
            new_name='Especie',
        ),
    ]
