# Generated by Django 4.2 on 2023-04-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0005_alter_animal_foto_alter_animal_idade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='cor',
            field=models.CharField(choices=[('preto', 'Preto'), ('branco', 'Branco'), ('cinza', 'Cinza'), ('marrom', 'Marrom'), ('caramelo', 'Caramelo')], default='preto', max_length=10, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('D', 'Disponivel para adoção'), ('A', 'Adoção em Andamento'), ('F', 'Adoção finalizada')], default='D', max_length=1, verbose_name='Status de adoção'),
        ),
    ]
