# Generated by Django 4.2 on 2023-04-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0006_alter_animal_cor_alter_animal_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raca',
            name='porte',
            field=models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], default='P', max_length=1, verbose_name='Porte'),
        ),
    ]
